import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Orbitron, Montserrat } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const orbitron = Orbitron({
  variable: "--font-orbitron", // Define CSS variable
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MemeBreaker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${orbitron.variable} ${montserrat.variable}`}><head>
    </head>
      <body >
        {children}
      </body>
    </html>
  );
}
